In [4]:
import open3d as o3d
import numpy as np

In [2]:
demo_crop_data = o3d.data.DemoCropPointCloud()
pcd = o3d.io.read_point_cloud(demo_crop_data.point_cloud_path)
vol = o3d.visualization.read_selection_polygon_volume(demo_crop_data.cropped_json_path)
chair = vol.crop_point_cloud(pcd)

[Open3D INFO] Downloading https://github.com/isl-org/open3d_downloads/releases/download/20220201-data/DemoCropPointCloud.zip
[Open3D INFO] Downloaded to /home/shpark/open3d_data/download/DemoCropPointCloud/DemoCropPointCloud.zip
[Open3D INFO] Created directory /home/shpark/open3d_data/extract/DemoCropPointCloud.
[Open3D INFO] Extracting /home/shpark/open3d_data/download/DemoCropPointCloud/DemoCropPointCloud.zip.
[Open3D INFO] Extracted to /home/shpark/open3d_data/extract/DemoCropPointCloud.


In [15]:
dists = pcd.compute_point_cloud_distance(chair)
dists = np.asarray(dists)

print(len(np.asarray(chair.points)))
print(np.asarray(chair.points))

print(len(np.asarray(pcd.points)))
print(np.asarray(pcd.points))

print(len(dists))
print(dists)
print(sum(dists)/len(dists))


31337
[[2.50390625 1.55034339 1.59765625]
 [2.51171875 1.5507381  1.59765625]
 [2.50390625 1.54788673 1.60546875]
 ...
 [2.6754024  2.40234375 1.65234375]
 [2.6723876  2.40234375 1.66015625]
 [2.66796875 2.40234375 1.6619457 ]]
196133
[[0.65234375 0.84686458 2.37890625]
 [0.65234375 0.83984375 2.38430572]
 [0.66737998 0.83984375 2.37890625]
 ...
 [2.00839925 2.39453125 1.88671875]
 [2.00390625 2.39488506 1.88671875]
 [2.00390625 2.39453125 1.88793314]]
196133
[1.82659798 1.83171046 1.817216   ... 0.27083108 0.27181889 0.27301031]
0.567234215707527


In [ ]:
import multiprocessing
chair_distances = []
compute_distance = lambda chair_point_cloud: np.asarray(pcd.compute_point_cloud_distance(chair_point_cloud))

for chair_point_cloud in chair_point_clouds:
  dists = compute_distance(chair_point_cloud)
  chair_distances.append(dists)

print(chair_distances)
# Define the function to compute distance
def compute_distance(chair_point_cloud):
  return np.asarray(pcd.compute_point_cloud_distance(chair_point_cloud))

# Create a pool of workers
pool = multiprocessing.Pool()

# Use the lambda function to compute distances in parallel
chair_distances = pool.map(lambda chair_point_cloud: compute_distance(chair_point_cloud), chair_point_clouds)

# Close the pool of workers
pool.close()
pool.join()

print(chair_distances)
