In [21]:
import numpy as np
import open3d as o3d

import torch

In [14]:
meshSphere = o3d.geometry.TriangleMesh.create_sphere()
print(meshSphere)
print(np.asarray(meshSphere.vertices))

TriangleMesh with 762 points and 1520 triangles.
[[ 0.          0.          1.        ]
 [ 0.          0.         -1.        ]
 [ 0.15643447  0.          0.98768834]
 ...
 [ 0.13938413 -0.07101976 -0.98768834]
 [ 0.14877802 -0.04834091 -0.98768834]
 [ 0.1545085  -0.02447174 -0.98768834]]


In [24]:
number_of_points = 1000
sampled_points = meshSphere.sample_points_uniformly(number_of_points)
sampled_points = torch.tensor(np.asarray(sampled_points.points))
print(sampled_points.shape)
print(sampled_points)

torch.Size([1000, 3])
tensor([[ 0.1032,  0.0281, -0.9916],
        [ 0.1077,  0.1057, -0.9881],
        [ 0.0126,  0.0511,  0.9958],
        ...,
        [ 0.1687, -0.1881, -0.9644],
        [ 0.2003, -0.1145, -0.9697],
        [ 0.2997, -0.0481, -0.9524]], dtype=torch.float64)
